"""empty message

Revision ID: 1caf4f13bec4
Revises: 
Create Date: 2022-07-24 13:54:10.908135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caf4f13bec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=125), nullable=False),
    sa.Column('provider', sa.String(length=125), nullable=False),
    sa.Column('score', sa.Float(precision=2), nullable=True),
    sa.Column('score_level', sa.Integer(), nullable=True),
    sa.Column('learner_count', sa.Integer(), nullable=True),
    sa.Column('lesson_count', sa.Integer(), nullable=True),
    sa.Column('lector_name', sa.String(length=125), nullable=True),
    sa.Column('original_price', sa.Float(precision=2), nullable=True),
    sa.Column('discount_price', sa.Float(precision=2), nullable=True),
    sa.Column('discount_rate', sa.Float(precision=2), nullable=True),
    sa.Column('img_url', sa.String(length=125), nullable=True),
    sa.Column('big_img_url', sa.String(length=125), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=125), nullable=False),
    sa.Column('learner_count', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('collections')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
